### ISSUE TITLE
Asynchronous Dialog Support

### ISSUE THREAD

**Issue by tneil** [blackberry/WebWorks#76] opened 2011-11-25 18:33 UTC
Add support to the Smartphone platform for [Asynchronous Dialogs]() (standardAskAsync, customAskAsync) like the PlayBook platform has.  This provides a consistent API between PlayBook and Smartphone and will allow for emulation in Ripple (not in scope of this issue).

Use the old style callback approach in order to reduce scope of this fix, unless we have a stable platform already for the event based approach.

This would mean that we mark the customAsk() and standardAsk() functions as "marked for deprecation" in the API reference and in the code.

Need to update docs as well.

**Comment by kwallis** [comment] 2012-01-30 18:46
Due to Smartphone API restrictions, the current optional "settings" parameter for the Async dialogs will NOT be supported in the Smartphone WebWorks SDK.  If it is provided, it should be gracefully ignored at runtime.

**Comment by kwallis** [comment] 2012-01-30 18:46
CC @dmateescu

**Comment by jachoi** [comment] 2012-02-03 14:05
I have created an java application which mimics WebWorks customAskAsync and as expected the dialog does not exit when the back button is pressed.

**Comment by kwallis** [comment] 2012-02-03 14:36
Do we have an idea of what it would take to fix this for WebWorks, and how

## long it would take?

Ken Wallis
Product Manager ­ BlackBerry WebWorks

Research In Motion
(905) 629-4746 x14369

-----Original Message-----
From: James Choi 
<reply+i-2351420-898775c7d3d1ef35b271a35c8a224e3b23bdf5aa-498318@reply.gith
ub.com>
Date: Fri, 3 Feb 2012 06:05:41 -0800
To: Ken Wallis kwallis@rim.com
Subject: Re: [WebWorks] Asynchronous Dialog Support (#76)

> I have created an java application which mimics WebWorks customAskAsync
> and as expected the dialog does not exit when the back button is pressed.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/blackberry/WebWorks/issues/76#issuecomment-3797114

---

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by kwallis** [comment] 2012-02-03 14:36
## And is there any workaround?

Ken Wallis
Product Manager ­ BlackBerry WebWorks

Research In Motion
(905) 629-4746 x14369

-----Original Message-----
From: James Choi 
<reply+i-2351420-898775c7d3d1ef35b271a35c8a224e3b23bdf5aa-498318@reply.gith
ub.com>
Date: Fri, 3 Feb 2012 06:05:41 -0800
To: Ken Wallis kwallis@rim.com
Subject: Re: [WebWorks] Asynchronous Dialog Support (#76)

> I have created an java application which mimics WebWorks customAskAsync
> and as expected the dialog does not exit when the back button is pressed.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/blackberry/WebWorks/issues/76#issuecomment-3797114

---

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by jachoi** [comment] 2012-02-03 14:44
I am currently trying to find a workaround and so far no luck. 
But I will continue looking into finding a workaround.

**Comment by tneil** [comment] 2012-02-03 14:56
I believe this is the same issue that is going on with the Back button with the new v2.3 navmode that is in the process of being fixed

**Comment by kwallis** [comment] 2012-02-03 15:00
This is a different issue.  We have fixed the back button issue for all of
the custom dialogs we create, like color and date etc.  However, for
customAskAsync, we farm back to the Java API to create the dialog.  It is
in the Java code for the dialog where the back button is not caught and

## closing the dialog.  A vanilla Java app exhibits the same issue.

Ken Wallis
Product Manager ­ BlackBerry WebWorks

Research In Motion
(905) 629-4746 x14369

-----Original Message-----
From: Tim Neil 
<reply+i-2351420-898775c7d3d1ef35b271a35c8a224e3b23bdf5aa-498318@reply.gith
ub.com>
Date: Fri, 3 Feb 2012 06:56:04 -0800
To: Ken Wallis kwallis@rim.com
Subject: Re: [WebWorks] Asynchronous Dialog Support (#76)

> I believe this is the same issue that is going on with the Back button
> with the new v2.3 navmode that is in the process of being fixed
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/blackberry/WebWorks/issues/76#issuecomment-3797816

---

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by jachoi** [comment] 2012-02-03 16:20
Good News, it looks I have found a workaround for back button for custom dialog issue and currently I have set it so that we would return the default choice indicated by the developer, is this we would want?

**Comment by jachoi** [comment] 2012-02-03 17:57
Correction in my last comment, the default choice is currently set to first choice in the list of choices.

**Comment by kwallis** [comment] 2012-02-03 18:19
What is returned on the StandardAsk when it is escaped?  Seems like a dev would not know when an actual selection was made versus the dialog was cancelled; this could be something the dev would want to know.

----- Original Message -----

**Comment by jachoi** [comment] 2012-02-03 18:32
StandardAsk returns blackberry.ui.dialog.C_CANCEL (which is -1) constant value.

**Comment by kwallis** [comment] 2012-02-03 22:16
## Can we be consistent here?

Ken Wallis
Product Manager ­ BlackBerry WebWorks

Research In Motion
(905) 629-4746 x14369

-----Original Message-----
From: James Choi 
<reply+i-2351420-898775c7d3d1ef35b271a35c8a224e3b23bdf5aa-498318@reply.gith
ub.com>
Date: Fri, 3 Feb 2012 10:32:58 -0800
To: Ken Wallis kwallis@rim.com
Subject: Re: [WebWorks] Asynchronous Dialog Support (#76)

> StandardAsk returns blackberry.ui.dialog.C_CANCEL (which is -1) constant
> value.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/blackberry/WebWorks/issues/76#issuecomment-3801707

---

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by jachoi** [comment] 2012-02-04 02:19
If you mean return the same value as standardAsk when the hardware back button is pressed, then it can be done.

**Comment by kwallis** [comment] 2012-02-04 02:20
Yup, sounds good.

----- Original Message -----

**Comment by kwallis** [comment] 2012-03-15 15:03
Included in 2.3.1 release

**Closed as completed by kwallis** 2012-03-15 15:03 UTC
Labels: Feature
